### ISSUE TITLE
Seeing a deprecation warning with erlavro using rebar 2

### ISSUE THREAD

**Issue by mrjoelkemp** [klarna/erlavro#113]
When doing mix compile or mix test commands on elixir 1.13.4 and erlang 24 and erlang 25, the following warning shows up (even on the latest erlavro release): 

```
dependency :erlavro is using Rebar 2, which is no longer maintained and no longer works in recent Erlang/OTP versions. Remove the :manager option or set it to :rebar3 instead
```

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/865203/171459801-5110d1c6-6bae-42ef-a89b-751c9ed9f2ad.png">

The suggested fix of listing the dependency in mix.exs as `{:erlavro, "~> 2.9.7", manager: :rebar3, override: true},` does remove the warning, but it seems like something may go wrong when newer elixir versions depend on erlang 25 and rebar2 is no longer supported.

**Comment by mikpe** [comment]
As far as I can tell, `erlavro` switched to `rebar3` by default back in 2018, though maintains support for `rebar2` if the user uses that. So it looks to me that its _your_ environment that sets `REBAR` to point to a `rebar2` binary.

Possibly we should just drop `rebar2` support and enforce `rebar3`.

**Comment by zmstone** [comment]
the magic is done here:  https://github.com/klarna/erlavro/blob/df5540bfc7215f80376e930257950c8bb8eda270/rebar.config.script#L1

**Comment by mikpe** [comment]
Published to hex

**Comment by chriseyre2000** [comment]
This issue can now be closed.

Thanks.
