### ISSUE TITLE
Default value \u0000 for bytes data type fails with `bad_default`

### ISSUE THREAD

**Issue by juanperi** [klarna/erlavro#126]
Hello there!!!

I'm having some problems decoding a bytes type with decimal as logical type, whenever the default value is set.

Example schema:
```
{
 "doc": "Testing decimals",
 "fields": [
   {
     "default": "\u0000",
     "name": "field",
     "type": {
       "logicalType": "decimal",
       "precision": 2,
       "scale": 1,
       "type": "bytes"
     }
   }
 ],
 "name": "sampleRecord",
 "namespace": "jperi",
 "type": "record"
}
```
The error I get from the elixir consumer is:
```
{:error,
{:bad_default,
 [record: "jperi.sampleRecord", field: "field", reason: :function_clause]}}
```

The issue can be circumvented if the `ignore_bad_default_values` is set to true.
But I don't think the default value is wrongly set. for a bytes type, it should be possible to set the default as `\u0000`. In the case of logical type decimal, that would mean that such values is a Zero.

I took a look at the code, but I'm not sure where a change to address this should go. (For example is it`parse`, `parse_bytes`? why does the `parse_bytes` has a `\\u00` at the beginning of the pattern match?).

The following diff makes the test suite of the library fail:

```diff
diff --git a/test/data/interop.avsc b/test/data/interop.avsc
index 8cfbba2..7be2c72 100644
--- a/test/data/interop.avsc
+++ b/test/data/interop.avsc
@@ -6,7 +6,7 @@
       {"name": "boolField", "type": "boolean"},
       {"name": "floatField", "type": "float"},
       {"name": "doubleField", "type": "double"},
-      {"name": "bytesField", "type": "bytes"},
+      {"name": "bytesField", "type": "bytes", "default": "\u0000"},
       {"name": "nullField", "type": "null"},
       {"name": "arrayField", "type": {"type": "array", "items": "double"}},
       {"name": "mapField", "type":
```

Do you think that this usecase is something that should be available to users of the library?

Thank you!!

**Comment by zmstone** [comment]
This is a bug.
`jsone` (the json library) already decoded `\u` escaped bytes.
`avro_json_decoder:parse_bytes` is however implemented to parse the original bytes.

**Comment by mikpe** [comment]
@zmstone just to make things crystal clear, are you saying that `avro_json_decode:parse_bytes` is in error for trying to repeat decoding already done by `jsone`?
If so I'll try to pick up this one, but I can't do any internal testing until the end of the month.

**Comment by zmstone** [comment]
Hi @mikpe 

> are you saying that avro_json_decode:parse_bytes is in error for trying to repeat decoding already done by jsone?

Yes.

> If so I'll try to pick up this one, but I can't do any internal testing until the end of the month.

Don't worry. I'll try to send a PR for this one in the next day or two.
