### ISSUE TITLE
Trouble decoding ocf files.

### ISSUE THREAD

**Issue by alanpeabody** [klarna/erlavro#36]
Hi!

I am having some trouble decoding some ocf files with this client that we have no issues with using a ruby client. If there is a better place to seek help please let me know and close this issue!

I have 2 simple avro schemas:

post.avro
```json
{
  "type": "record",
  "name": "post_event",
  "fields": [
    { "name": "id", "type": "string" },
    { "name": "created_at", "type": "double" },
    { "name": "body", "type": "string" },
    { "name": "nsfw", "type": "boolean" },
    { "name": "url", "type": "string" }
  ]
}
```

post_was_loved.avro (stripped to smallest failing schema)
```json
[
  {
    "type": "record",
    "name": "post_was_loved",
    "fields" : [
      { "name": "post", "type": "post" }
    ]
  }
]
```

avro_ocf.decode_file/1 works fine with the first schema, however when trying to import the second I get a error:

```
** (ErlangError) erlang error: {:unnamed_type, {:avro_union_type, {1, {0, "post_was_loved", nil, nil}}, {1, {"post_was_loved", {0, true}, nil, nil}}}}
    (erlavro) /Users/alan/Ello/ello_event_stream/deps/erlavro/src/avro_schema_store.erl:161: :avro_schema_store.add_type/3
    (erlavro) /Users/alan/Ello/ello_event_stream/deps/erlavro/src/avro_ocf.erl:65: :avro_ocf.decode_file/1
```

(Note I am using Elixir and the master branch of this repo)

I am not an avro (nor erlang!) expert so I am very likely doing something wrong, but any guidance or troubleshooting advice would be very appreciated!

Thanks for the hard work on this repo!

**Comment by alanpeabody** [comment]
And as soon as I posted this I identified the issue. Of course :-D.

It was the top level array wrapping the post was loved schema.

**Comment by zmstone** [comment]
@alanpeabody Root level union type is currently not supported for ocf.
I guess you made it work because you don't have to use a union in your case.
But there might be other users who needs union at root level.
I'll fix it.

**Comment by alanpeabody** [comment]
Thanks @zmstone !
