### ISSUE TITLE
Cannot import files in Elixir 1.4.4

### ISSUE THREAD

**Issue by duytruong** [klarna/erlavro#42]
Hi there,

[My application](https://github.com/duytruong/collector/blob/master/lib/collector/avro_encoder.ex) use erlavro to encode message in avro format and produce to Kafka, it worked well before, but today I start it and receive following error

`** (Mix) Could not start application collector: Collector.Application.start(:normal, []) returned an error: shutdown: failed to start child: Collector.AvroEncoder
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in :avro_schema_store.import_files/2
            (erlavro) /media/duyrau/WORK/LEARNING/Elixir/collector/deps/erlavro/src/avro_schema_store.erl:108: :avro_schema_store.import_files(['schema/click.avsc'], #Reference<0.2588577052.1602355204.236674>)
            (collector) lib/collector/avro_encoder.ex:9: Collector.AvroEncoder.init/1
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
`

My code isn't changed, it worked when I use Elixir 1.4.2, now I update to 1.4.4 and it crash.
Elixir version

`Erlang/OTP 20 [RELEASE CANDIDATE 2] [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.4.4
`

What should I do?

Thanks

**Comment by zmstone** [comment]
Please check what is passed as the second arg in the call to :avro_schema_store.import_files/2
ETS table (the result of :acro_schema_store.new) is expected, but it's a reference in the crash log.

**Comment by michalmuskala** [comment]
OTP 20 changed the opaque table identifiers to be references instead of integers. It was never correct of `erlavro` to assume a table identifier to be an integer - the representation was always documented as opaque.

**Comment by zmstone** [comment]
published to hex. 2.1.1
