### ISSUE TITLE
make error in erlang/otp 21

### ISSUE THREAD

**Issue by Gilbert-Wong** [klarna/erlavro#71]
**Environment**

* OS: Mac OS 10.13.5
* Erlang/OTP: 21
* erlavro: branch master

**Description**
When I git clone this repo and make it on mac. It shows error while compiling jsone.erl:
```
rebar3 get-deps
===> Verifying dependencies...
rebar3 compile
===> Verifying dependencies...
===> Compiling jsone
===> Compiling _build/default/lib/jsone/src/jsone.erl failed
_build/default/lib/jsone/src/jsone.erl:294: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
_build/default/lib/jsone/src/jsone.erl:343: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

make: *** [compile] Error 1
```

And I tried to make it on my ubuntu server which erlang/otp version is 20. It makes successfully.
So I think may be you need to use new syntax to  retrieve the stack backtrace.

**Comment by reachfh** [comment]
Fixed in 2.6.2
