### ISSUE TITLE
support for map

### ISSUE THREAD

**Issue by ananthakumaran** [klarna/erlavro#85]
is there any plan to add support for map data structure. am I correct in assuming the current format `[{key, val}]` is used for record/map type because when the project started there was no map in erlang?

**Comment by zmstone** [comment]
We have thought about adding `map()` support as encoder input,
and maybe allow an option to make decoder return maps too,
but never got time for it.

And it's correct that we started when there is no `map()` in Erlang.

**Comment by zmstone** [comment]
fixed in: https://github.com/klarna/erlavro/pull/86

**Comment by zmstone** [comment]
@jochasinga yes, but a lot more than that. you can find the changes in #86 .
issue closed, thanks a lot @ananthakumaran
